name: mediconnect_app
description: "Un sistema de gestión dual (médico/paciente) completo para clínicas pequeñas"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/

flutter_launcher_icons:
  android: true
  image_path: "assets/logo.png"